"""Suite configuration for reusable one-shot live target tests."""

from __future__ import annotations

import os


BASE_URL = os.getenv("BASE_URL") or None
SUITE_NAME = "one_shot"

SMOKE_HEALTH_PATH = os.getenv("ONE_SHOT_SMOKE_HEALTH_PATH", "/")
SMOKE_HEALTH_STATUS = int(os.getenv("ONE_SHOT_SMOKE_HEALTH_STATUS", "200"))
SMOKE_ROOT_PATH = os.getenv("ONE_SHOT_SMOKE_ROOT_PATH", "/")
SMOKE_ROOT_SELECTOR = os.getenv("ONE_SHOT_SMOKE_ROOT_SELECTOR", "body")
SMOKE_REQUEST_TIMEOUT_MS = int(os.getenv("ONE_SHOT_SMOKE_REQUEST_TIMEOUT_MS", "5000"))
SMOKE_RENDER_TIMEOUT_MS = int(os.getenv("ONE_SHOT_SMOKE_RENDER_TIMEOUT_MS", "8000"))

PERF_HOME_PATH = os.getenv("ONE_SHOT_PERF_HOME_PATH", "/")
PERF_HOME_READY_SELECTOR = os.getenv("ONE_SHOT_PERF_HOME_READY_SELECTOR", "body")
PERF_MOBILE_PATH = os.getenv("ONE_SHOT_PERF_MOBILE_PATH", "/")
PERF_MOBILE_READY_SELECTOR = os.getenv("ONE_SHOT_PERF_MOBILE_READY_SELECTOR", "body")
PERFORMANCE_MAX_RESPONSE_MS = float(os.getenv("PERFORMANCE_MAX_RESPONSE_MS", "5000"))
PERFORMANCE_MAX_TTFB_MS = float(os.getenv("PERFORMANCE_MAX_TTFB_MS", "800"))
PERFORMANCE_MAX_LOAD_MS = float(os.getenv("PERFORMANCE_MAX_LOAD_MS", "3000"))
PERFORMANCE_MAX_MOBILE_INTERACTIVE_MS = float(
    os.getenv("PERFORMANCE_MAX_MOBILE_INTERACTIVE_MS", "10000")
)
PERFORMANCE_WARMUP_RUNS = int(os.getenv("PERFORMANCE_WARMUP_RUNS", "1"))
PERFORMANCE_SAMPLE_COUNT = int(os.getenv("PERFORMANCE_SAMPLE_COUNT", "3"))
PERFORMANCE_MOBILE_LATENCY_MS = int(os.getenv("PERFORMANCE_MOBILE_LATENCY_MS", "300"))
PERFORMANCE_MOBILE_DOWNLOAD_KBPS = int(os.getenv("PERFORMANCE_MOBILE_DOWNLOAD_KBPS", "400"))
PERFORMANCE_MOBILE_UPLOAD_KBPS = int(os.getenv("PERFORMANCE_MOBILE_UPLOAD_KBPS", "150"))
PERFORMANCE_MOBILE_CPU_THROTTLE_RATE = int(
    os.getenv("PERFORMANCE_MOBILE_CPU_THROTTLE_RATE", "4")
)
PERFORMANCE_MOBILE_PROFILE_NAME = os.getenv("PERFORMANCE_MOBILE_PROFILE_NAME", "slow_3g_like")

SECURITY_SEARCH_PATH = os.getenv("ONE_SHOT_SECURITY_SEARCH_PATH", "/")
SECURITY_SEARCH_INPUT_SELECTOR = os.getenv(
    "ONE_SHOT_SECURITY_SEARCH_INPUT_SELECTOR",
    "input[type='search'], input[name='search'], input[type='text']",
)
SECURITY_SEARCH_SUBMIT_SELECTOR = os.getenv(
    "ONE_SHOT_SECURITY_SEARCH_SUBMIT_SELECTOR",
    "button[type='submit'], input[type='submit']",
)
SECURITY_CONSENT_ROOT_SELECTOR = os.getenv("ONE_SHOT_SECURITY_CONSENT_ROOT_SELECTOR", ".fc-consent-root")
SECURITY_CONSENT_ACCEPT_SELECTOR = os.getenv(
    "ONE_SHOT_SECURITY_CONSENT_ACCEPT_SELECTOR",
    ".fc-cta-consent, button:has-text('Consent'), button:has-text('Accept')",
)
