"""Website-specific suite configuration."""

import os

BASE_URL = "https://www.sabre.com"
SUITE_NAME = "sabre_com"
SMOKE_HEALTH_PATH = "/"
SMOKE_HEALTH_STATUS = 200
SMOKE_ROOT_PATH = "/"
SMOKE_ROOT_SELECTOR = "body"
SMOKE_REQUEST_TIMEOUT_MS = 5_000
SMOKE_RENDER_TIMEOUT_MS = 8_000
PERF_HOME_PATH = "/"
PERF_HOME_READY_SELECTOR = "body"
PERF_MOBILE_PATH = "/"
PERF_MOBILE_READY_SELECTOR = "body"
PERFORMANCE_MAX_RESPONSE_MS = float(os.getenv("PERFORMANCE_MAX_RESPONSE_MS", "5000"))
PERFORMANCE_MAX_TTFB_MS = float(os.getenv("PERFORMANCE_MAX_TTFB_MS", "800"))
PERFORMANCE_MAX_LOAD_MS = float(os.getenv("PERFORMANCE_MAX_LOAD_MS", "3000"))
PERFORMANCE_MAX_MOBILE_INTERACTIVE_MS = float(os.getenv("PERFORMANCE_MAX_MOBILE_INTERACTIVE_MS", "10000"))
PERFORMANCE_WARMUP_RUNS = int(os.getenv("PERFORMANCE_WARMUP_RUNS", "1"))
PERFORMANCE_SAMPLE_COUNT = int(os.getenv("PERFORMANCE_SAMPLE_COUNT", "3"))
PERFORMANCE_MOBILE_LATENCY_MS = int(os.getenv("PERFORMANCE_MOBILE_LATENCY_MS", "300"))
PERFORMANCE_MOBILE_DOWNLOAD_KBPS = int(os.getenv("PERFORMANCE_MOBILE_DOWNLOAD_KBPS", "400"))
PERFORMANCE_MOBILE_UPLOAD_KBPS = int(os.getenv("PERFORMANCE_MOBILE_UPLOAD_KBPS", "150"))
PERFORMANCE_MOBILE_CPU_THROTTLE_RATE = int(os.getenv("PERFORMANCE_MOBILE_CPU_THROTTLE_RATE", "4"))
PERFORMANCE_MOBILE_PROFILE_NAME = os.getenv("PERFORMANCE_MOBILE_PROFILE_NAME", "slow_3g_like")
SECURITY_SEARCH_PATH = "/"
SECURITY_SEARCH_TRIGGER_SELECTOR = "a.search"
SECURITY_SEARCH_TRIGGER_ACTIVE_SELECTOR = "a.search.is-active"
SECURITY_SEARCH_PANEL_SELECTOR = ".site-header__main--search-panel"
SECURITY_SEARCH_PANEL_ACTIVE_SELECTOR = ".site-header__main--search-panel.is-active"
SECURITY_SEARCH_INPUT_SELECTOR = "input[type='search'], input[name='search'], input[type='text']"
SECURITY_SEARCH_SUBMIT_SELECTOR = "button[type='submit'], input[type='submit']"
SECURITY_CONSENT_ROOT_SELECTOR = ".fc-consent-root"
SECURITY_CONSENT_ACCEPT_SELECTOR = (
    ".fc-cta-consent, button:has-text('Consent'), "
    "button:has-text('Accept')"
)
SECURITY_CONSENT_OVERLAY_SELECTOR = ".fc-dialog-overlay"
